# Generated by Django 4.1.5 on 2024-05-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('desigination', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='media/uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('whatsapp', models.URLField(blank=True, max_length=300, null=True)),
                ('instagram', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter', models.URLField(blank=True, max_length=300, null=True)),
                ('linkdin', models.URLField(blank=True, max_length=300, null=True)),
                ('facebook', models.URLField(blank=True, max_length=300, null=True)),
                ('website1', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
