# Generated by Django 4.1.5 on 2024-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicbussinesscard', '0002_remove_client_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
