# Generated by Django 4.1.5 on 2024-08-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nicbussinesscard', '0007_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nicbussinesscard.demo')),
            ],
        ),
    ]
