# Generated by Django 4.1.5 on 2024-08-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicbussinesscard', '0008_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='price',
            new_name='amount',
        ),
    ]
