# Generated by Django 4.1.5 on 2024-08-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicbussinesscard', '0009_rename_price_demo_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='amount',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=567),
            preserve_default=False,
        ),
    ]
