# Generated by Django 4.1.5 on 2024-08-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicbussinesscard', '0010_alter_demo_amount_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='remark',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
